version: "3.3"

services:
    openapi_generator:
        image: openapitools/openapi-generator-online:latest-release
        ports:
            - "8081:8080"
        depends_on:
          - mongo
          - celery
        networks:
            backend:
                ipv4_address: 10.0.0.10
        volumes:
            - ./app/:/app

    redis_server:
        image: redis
        command: redis-server
        networks:
            backend:
                ipv4_address: 10.0.0.3
    flower:
        build:
            context: ./
            dockerfile: ./Dockerfile
        command: flower
        ports:
            - "5555:5555"
        environment:
            FLOWER_PORT: 5555
            REDIS_URI: redis://:@10.0.0.3:6379
        depends_on:
            - mongo
            - celery
        networks:
            backend:
                ipv4_address: 10.0.0.6
        volumes:
            - ./app/:/app
    api:
        build:
            context: ./
            dockerfile: ./Dockerfile
        command: api
        ports:
            - "8000:8000"
        environment:
            OPENAPI_GENERATOR: 10.0.0.10:8080
            MONGO_IP: 10.0.0.5
            FLOWER_PORT: 8080
            ADMIN_USER: admin2
            ADMIN_PASS: admin
            REDIS_URI: redis://:@10.0.0.3:6379
        depends_on:
            - mongo
            - celery
        networks:
            backend:
                ipv4_address: 10.0.0.100
        volumes:
            - ./app/:/app
    workers:
        build:
            context: ./
            dockerfile: ./Dockerfile
        command: workers
        environment:
            OPENAPI_GENERATOR: 10.0.0.10:8080
            MONGO_IP: 10.0.0.5
            REDIS_URI: redis://:@10.0.0.3:6379
        depends_on:
            - mongo
            - celery
        networks:
            backend:
                ipv4_address: 10.0.0.4
        volumes:
            - ./app/:/app
    mongo:
        image: mongo
        container_name: mongo-db
        volumes:
            - ./data/db:/data/db
        ports:
            - "27017:27017"
        restart: unless-stopped
        networks:
            backend:
                ipv4_address: 10.0.0.5

networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.0.0/24
